export const news = [
  {
    news_url: "https://cryptodaily.co.uk/2023/07/crypto-exchange-lbank-launches-cryptocurrency-credit-card",
    image_url: "https://crypto.snapi.dev/images/v1/j/m/lbank-327782.jpg",
    title: "Crypto Exchange LBank Launches Cryptocurrency Credit Card",
    text: "Cryptocurrency exchange LBank has announced the launch of the first unlimited crypto credit card. According to a press release, world-leading crypto exchange LBank announced the launch of the world's first unlimited cryptocurrency credit card.",
    source_name: "Crypto Daily",
    date: "Mon, 03 Jul 2023 05:49:03 -0400",
    topics: [],
    sentiment: "Positive",
    type: "Article",
  },
  {
    news_url:
      "https://thecurrencyanalytics.com/regulations/thailand-sec-strengthens-investor-protection-in-cryptocurrency-market-what-you-need-to-know-57140.php",
    image_url: "https://crypto.snapi.dev/images/v1/a/0/0vy4eb08-327780.png",
    title: "Thailand SEC Strengthens Investor Protection in Cryptocurrency Market: What You Need to Know",
    text: "In a groundbreaking move, Thailand's Securities and Exchange Commission (SEC) has taken decisive action to fortify investor protection within the rapidly evolving cryptocurrency industry. By introducing comprehensive new guidelines, the SEC aims to provide unparalleled clarity on risk warnings and impose crucial restrictions on deposit and lending services offered by digital asset business operators.",
    source_name: "The Currency Analytics",
    date: "Mon, 03 Jul 2023 05:45:51 -0400",
    topics: [],
    sentiment: "Positive",
    type: "Article",
  },
  {
    news_url:
      "https://www.theblock.co/post/237452/attacker-pockets-10-million-from-poly-network-security-attack-beosin",
    image_url: "https://crypto.snapi.dev/images/v1/v/o/20230411-hack-generic-2-800x450-327783.jpg",
    title: "Attacker pockets $10 million from Poly Network security attack: Beosin",
    text: "The Poly Network attacker illicitly minted varying amounts of 57 tokens across 10 blockchains, including Ethereum, BNB Chain and Metis.",
    source_name: "The Block",
    date: "Mon, 03 Jul 2023 05:45:43 -0400",
    topics: [],
    sentiment: "Negative",
    type: "Article",
  },
  {
    news_url:
      "https://www.theblock.co/post/237452/attacker-pockets-10-million-from-poly-network-security-attack-beosin",
    image_url: "https://crypto.snapi.dev/images/v1/v/o/20230411-hack-generic-2-800x450-327783.jpg",
    title: "Attacker pockets $10 million from Poly Network security attack: Beosin",
    text: "The Poly Network attacker illicitly minted varying amounts of 57 tokens across 10 blockchains, including Ethereum, BNB Chain and Metis.",
    source_name: "The Block",
    date: "Mon, 03 Jul 2023 05:45:43 -0400",
    topics: [],
    sentiment: "Negative",
    type: "Article",
  },
  {
    news_url: "https://coinpedia.org/news/south-korea-prioritizes-crypto-users-new-bill-ensures-enhanced-protection/",
    image_url:
      "https://crypto.snapi.dev/images/v1/7/9/bitcoin-receives-non-money-status-in-south-korean-court-ruling-327769.webp",
    title: "South Korea Prioritizes Crypto Users: New Bill Ensures Enhanced Protection",
    text: "South Korea's National Assembly has approved the Virtual Asset User Protection Act, representing a significant step in establishing a legal framework for virtual assets within the country. The legislation, composed of 19 proposals from lawmakers, aims to define digital assets and address unfair transactions by implementing penalties.",
    source_name: "CoinPedia",
    date: "Mon, 03 Jul 2023 05:21:16 -0400",
    topics: [Array],
    sentiment: "Positive",
    type: "Article",
  },
  {
    news_url:
      "https://thecurrencyanalytics.com/regulations/belarus-cracks-down-on-crypto-criminals-with-bold-ban-on-p2p-transfers-57127.php",
    image_url: "https://crypto.snapi.dev/images/v1/c/l/3qb9etmj-327766.png",
    title: "Belarus Cracks Down on Crypto Criminals with Bold Ban on P2P Transfers",
    text: "In a decisive move to combat cybercrime and strengthen its fight against illicit activities, the Ministry of Internal Affairs of Belarus has announced its intention to introduce a groundbreaking bill. This proposed legislation aims to ban the transfer of cryptocurrencies among individuals, sending shockwaves through the nation's crypto community.",
    source_name: "The Currency Analytics",
    date: "Mon, 03 Jul 2023 05:15:13 -0400",
    topics: [],
    sentiment: "Negative",
    type: "Article",
  },
  {
    news_url: "https://cointelegraph.com/news/belarus-wants-to-ban-p2p-cryptocurrency-transactions",
    image_url: "https://crypto.snapi.dev/images/v1/m/n/b6366f74-21b2-412d-a8c1-4e2cb0b0e833-327765.jpg",
    title: "Belarus wants to ban P2P cryptocurrency transactions",
    text: "Belarus' Ministry of Foreign Affairs cited a high crypto crime rate for banning all citizens from exchanging Bitcoin between each other.",
    source_name: "Cointelegraph",
    date: "Mon, 03 Jul 2023 05:10:54 -0400",
    topics: [],
    sentiment: "Negative",
    type: "Article",
  },
  {
    news_url: "https://coinspress.com/russian-citizen-arrested-for-donating-crypto-to-ukrainian-army/?SNAPI",
    image_url: "https://crypto.snapi.dev/images/v1/x/w/arrested-handcuffs-327762.webp",
    title: "Russian Citizen Arrested for Donating Crypto to Ukrainian Army",
    text: "A Russian citizen named Alexander Vecherko from the Khabarovsk Krai region has been arrested for allegedly donating cryptocurrencies to support the Ukrainian army.",
    source_name: "Coinspress",
    date: "Mon, 03 Jul 2023 05:00:56 -0400",
    topics: [],
    sentiment: "Negative",
    type: "Article",
  },
  {
    news_url:
      "https://thecurrencyanalytics.com/finance/revolutionizing-the-future-hong-kong-takes-the-lead-in-web3-innovation-with-groundbreaking-task-force-57121.php",
    image_url: "https://crypto.snapi.dev/images/v1/r/d/e6669e5s-327760.png",
    title: "Revolutionizing the Future: Hong Kong Takes the Lead in Web3 Innovation with Groundbreaking Task Force",
    text: "Hong Kong, a global financial hub known for its forward-thinking approach, has once again demonstrated its commitment to embracing technological innovation with the establishment of a task force dedicated to Web3 technology. Announced on June 30, the task force is set to play a crucial role in overseeing the sustainable and responsible development of Web3 within the region, cementing Hong Kong's position as a frontrunner in this transformative sector.",
    source_name: "The Currency Analytics",
    date: "Mon, 03 Jul 2023 05:00:49 -0400",
    topics: [],
    sentiment: "Positive",
    type: "Article",
  },
  {
    news_url:
      "https://thecurrencyanalytics.com/finance/revolutionizing-the-future-hong-kong-takes-the-lead-in-web3-innovation-with-groundbreaking-task-force-57121.php",
    image_url: "https://crypto.snapi.dev/images/v1/r/d/e6669e5s-327760.png",
    title: "Revolutionizing the Future: Hong Kong Takes the Lead in Web3 Innovation with Groundbreaking Task Force",
    text: "Hong Kong, a global financial hub known for its forward-thinking approach, has once again demonstrated its commitment to embracing technological innovation with the establishment of a task force dedicated to Web3 technology. Announced on June 30, the task force is set to play a crucial role in overseeing the sustainable and responsible development of Web3 within the region, cementing Hong Kong's position as a frontrunner in this transformative sector.",
    source_name: "The Currency Analytics",
    date: "Mon, 03 Jul 2023 05:00:49 -0400",
    topics: [],
    sentiment: "Positive",
    type: "Article",
  },
  {
    news_url: "https://coingape.com/?p=153255",
    image_url: "https://crypto.snapi.dev/images/v1/q/z/belarus-crypto-327755.jpg",
    title: "Belarus Bans Transfer of Cryptocurrencies Among Individuals, Here's Why",
    text: "In a recent development, the Ministry of Internal Affairs of Belarus announced that it's working on a bill to ban the transfer of cryptocurrencies among individuals. The department noted that the move will help fight the withdrawal of money earned through criminal means.",
    source_name: "Coingape",
    date: "Mon, 03 Jul 2023 04:49:32 -0400",
    topics: [],
    sentiment: "Neutral",
    type: "Article",
  },
  {
    news_url:
      "https://www.coindesk.com/policy/2023/07/03/singapores-mas-orders-crypto-firms-to-keep-customer-assets-in-a-trust-by-year-end/",
    image_url: "https://crypto.snapi.dev/images/v1/y/y/glcwdpo6tnhzrhnjc6c562ptu4-327753.jpg",
    title: "Singapore's MAS Orders Crypto Firms to Keep Customer Assets in a Trust by Year-End",
    text: "Crypto service providers in Singapore are now required to safekeep customer assets under a statutory trust before the end of the year.",
    source_name: "Coindesk",
    date: "Mon, 03 Jul 2023 04:42:46 -0400",
    topics: [],
    sentiment: "Positive",
    type: "Article",
  },
  {
    news_url: "https://www.coinspeaker.com/poly-network-attackers-billions-tokens/",
    image_url: "https://crypto.snapi.dev/images/v1/w/m/crypto19-327749.jpg",
    title: "Poly Network Suspends Operations after Attackers Mint Billions of Tokens",
    text: "The attackers manipulated nearly 57 assets across 10 different blockchains and created nearly $42 billion in tokens immediately after the attack.",
    source_name: "Coinspeaker",
    date: "Mon, 03 Jul 2023 04:42:41 -0400",
    topics: [],
    sentiment: "Negative",
    type: "Article",
  },
  {
    news_url: "https://cointelegraph.com/news/belarus-wants-to-ban-p2p-cryptocurrency-transactions",
    image_url: "https://crypto.snapi.dev/images/v1/m/n/b6366f74-21b2-412d-a8c1-4e2cb0b0e833-327765.jpg",
    title: "Belarus wants to ban P2P cryptocurrency transactions",
    text: "Belarus' Ministry of Foreign Affairs cited a high crypto crime rate for banning all citizens from exchanging Bitcoin between each other.",
    source_name: "Cointelegraph",
    date: "Mon, 03 Jul 2023 05:10:54 -0400",
    topics: [],
    sentiment: "Negative",
    type: "Article",
  },
  {
    news_url: "https://coinspress.com/russian-citizen-arrested-for-donating-crypto-to-ukrainian-army/?SNAPI",
    image_url: "https://crypto.snapi.dev/images/v1/x/w/arrested-handcuffs-327762.webp",
    title: "Russian Citizen Arrested for Donating Crypto to Ukrainian Army",
    text: "A Russian citizen named Alexander Vecherko from the Khabarovsk Krai region has been arrested for allegedly donating cryptocurrencies to support the Ukrainian army.",
    source_name: "Coinspress",
    date: "Mon, 03 Jul 2023 05:00:56 -0400",
    topics: [],
    sentiment: "Negative",
    type: "Article",
  },
  {
    news_url:
      "https://thecurrencyanalytics.com/finance/revolutionizing-the-future-hong-kong-takes-the-lead-in-web3-innovation-with-groundbreaking-task-force-57121.php",
    image_url: "https://crypto.snapi.dev/images/v1/r/d/e6669e5s-327760.png",
    title: "Revolutionizing the Future: Hong Kong Takes the Lead in Web3 Innovation with Groundbreaking Task Force",
    text: "Hong Kong, a global financial hub known for its forward-thinking approach, has once again demonstrated its commitment to embracing technological innovation with the establishment of a task force dedicated to Web3 technology. Announced on June 30, the task force is set to play a crucial role in overseeing the sustainable and responsible development of Web3 within the region, cementing Hong Kong's position as a frontrunner in this transformative sector.",
    source_name: "The Currency Analytics",
    date: "Mon, 03 Jul 2023 05:00:49 -0400",
    topics: [],
    sentiment: "Positive",
    type: "Article",
  },
];
